Feature/menu design
UKHomeOffice/centre-of-excellence pull request #2
Opened 2017-01-20 10:11 UTC by sulthan-ahmed

* Make the navigation menu look better and follow a home office pattern
* Move the menu out of the content area for accessibility and good code practice. Sort out the GDS styling as a result of this

**Styling before**
<img width="1271" alt="screen shot 2017-01-20 at 10 08 09" src="https://cloud.githubusercontent.com/assets/12494656/22145323/b18ac9c6-def8-11e6-845c-9ad689a6d73b.png">

**Styling after**
<img width="1280" alt="screen shot 2017-01-20 at 10 08 42" src="https://cloud.githubusercontent.com/assets/12494656/22145334/bdde77d6-def8-11e6-8528-a3faa7ead569.png">

2017-01-20 10:27 UTC, chrisns requested changes
DRY
also, as an aside, shouldn't the page title be `Home Office Centre of Excellence`?

2017-01-20 10:27 UTC, chrisns commented on views/best-practices.html
> +<div class="navbar">
use standard `<nav>` element?

2017-01-20 10:27 UTC, chrisns commented on views/engagement.html
> +<div class="navbar">
why are you having to copy paste this into every file?! seems mental

2017-01-20 11:07 UTC, sulthan-ahmed commented on views/best-practices.html
> +<div class="navbar">
good point

2017-01-20 11:13 UTC, sulthan-ahmed commented on views/engagement.html
> +<div class="navbar">
Yeah it's totally mental :face_with_head_bandage:  .  Every menu is the same except when it refers to that particular page.  I'll try to see how to do this better

2017-01-20 11:14 UTC, sulthan-ahmed commented
fair point @chrisns . Also, I don't think we should even be calling it the centre of excellence as it's a different thing altogether but yes I can add Home Office to it

2017-01-20 14:09 UTC, chrisns commented
in terms of title, its only so it makes sense since so someone can know where they are given the only other thing in the near the title is 'gov.uk'

2017-01-23 09:35 UTC, chrisns commented on views/best-practices.html
> +  <section class="intro">
hard to judge based on the lorem ipsum.
the page should only have one `H1` and that should be the page title, so not sure it makes sense to put that in a `<section>`
also not sure why you ditched using `<main>`

2017-02-10 11:43 UTC, sulthan-ahmed commented on views/best-practices.html
> +  <section class="intro">
fair point, I've moved the <h1> out of the section

main is inside layout.html which is shared https://github.com/UKHomeOffice/centre-of-excellence/pull/2/files#diff-6451baa0fcad2e1932fbce8f11535c95R23

I do only have one h1.  I didn't quite understand having the page title as a h1.  How do you do that?

2017-02-10 14:53 UTC, daniel-ac-martin commented
LGTM.

2017-02-10 14:53 UTC, chrisns commented on views/best-practices.html
> +  <h1>Best Practices</h1>
given this is common, can you template an `<h1>${{pageTitle}}</h1>` in the layout appearing above the content rather than repeating it everywhere?

2017-02-14 16:13 UTC, sulthan-ahmed commented on views/best-practices.html
> +  <h1>Best Practices</h1>
good idea, I've done as you've suggested

2017-02-15 12:03 UTC, chrisns approved these changes

2017-02-15 14:21 UTC, sulthan-ahmed commented
Yayy 🎆 
thanks @daniel-ac-martin and @chrisns

2017-02-15 14:21 UTC, merged